# Generated by Django 5.0.6 on 2024-06-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=25)),
                ('ln', models.CharField(max_length=20)),
                ('sub', models.CharField(max_length=15)),
                ('loc', models.CharField(max_length=15)),
                ('sal', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
